local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/images"
public_folder: "/assets/images"
site_url: "https://Tech-Informal.web.app"
display_url: "https://Tech-Informal.web.app"
logo_url: "https://tech-informal.web.app/assets/images/favicon.png"
show_preview_links: true
search: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Type", name: "type", widget: "list", default: ["blog"] }

  - name: "article"
    label: "Article"
    folder: "src/article"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "article/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["article"] }
      - { label: "Type", name: "type", widget: "list", default: ["article"] }
